Update azure-pipelines.yml with an example from https://github.com/rstropek/gophers-azure-pipelines/blob/master/azure-pipelines.yml

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,22 +1,45 @@
-pool:
-  vmImage: ubuntu-latest
+trigger:
+- master
 
-steps:
-- task: CopyFiles@2
-  inputs:
-    Contents: '**'
-    TargetFolder: '$(Build.ArtifactStagingDirectory)'
+stages:
+- stage: 'BuildTest'
+  displayName: 'Build and Test'
+  variables:
+    GOVERSION: '1.13.5'   # Version of Go tools used for building and testing
+    CGO_ENABLED: '0'      # Disable cgo to get a static binary
+    GOOS: 'linux'
+    GOARCH: 'amd64'
+  jobs:
+  - job: BuildTestBackend
+    displayName: 'Build and Test Go Backend'
+    pool:
+      vmImage: 'Ubuntu 18.04'
+    steps:
+    - task: GoTool@0
+      inputs:
+        version: $(GOVERSION)
+      displayName: 'Install and select Go version $(GOVERSION)'
 
-- task: PublishBuildArtifacts@1
-  inputs:
-    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
-    ArtifactName: 'drop'
-
-- task: GoTool@0
-  inputs:
-    version: '1.15'
+    - script: |
+        # Get tools for converting Go's test reports
+        go get -u github.com/jstemmer/go-junit-report 2>&1
+        go get -u github.com/axw/gocov/gocov 2>&1
+        go get -u github.com/AlekSi/gocov-xml 2>&1
+        # Run Go tests and turn output into JUnit test result format
+        go test ./mathalgorithms -v -coverprofile=demo-coverage.txt -covermode count 2>&1 | $HOME/go/bin/go-junit-report > demo-report.xml
+        rc=${PIPESTATUS[0]} # Get result code of `go test`
+        # Convert coverage file into XML
+        $HOME/go/bin/gocov convert demo-coverage.txt > demo-coverage.json
+        $HOME/go/bin/gocov-xml < demo-coverage.json > demo-coverage.xml
+        # Check if `go test` had an error
+        if [ $rc -ne 0 ]; then
+          # Let script fail by writing to stderr
+          >&2 echo "Tests failed"
+        fi
+      displayName: 'Run unit tests and convert results'
+      failOnStderr: true
     
-- task: Go@0
-  inputs:
-    command: 'build'
-    workingDirectory: '$(Build.ArtifactStagingDirectory)/main' 
+    - task: Go@0
+      inputs:
+        command: 'build'
+        workingDirectory: '$(Build.ArtifactStagingDirectory)/main' 
